name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: molecule-web

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install
        working-directory: molecule-web

      - name: Build site
        run: pnpm docs:build
        working-directory: molecule-web

      - name: List built files
        run: ls -R docs/.vuepress/dist
        working-directory: molecule-web

      - name: Deploy to scalamolecule.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: scalamolecule/scalamolecule.github.io
          publish_branch: master
          publish_dir: molecule-web/docs/.vuepress/dist
          cname: www.scalamolecule.org
          verbose: trueÏ€