name: Deploy VuePress site to GitHub Pages

on:
  push:
    branches:
      - master  # or 'main' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          path: .  # checkout directly into the working directory

      - name: Print working directory and tree (debug)
        run: |
          pwd
          ls -al
          ls pnpm-lock.yaml || echo "Still missing lock file"


      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable and activate pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@8.15.5 --activate
          pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Build VuePress site
        run: pnpm docs:build

      - name: List built files (debug)
        run: ls -R docs/.vuepress/dist

      - name: Deploy to scalamolecule.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: scalamolecule/scalamolecule.github.io
          publish_branch: master
          publish_dir: docs/.vuepress/dist
          cname: www.scalamolecule.org