name: Deploy VuePress site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          path: molecule-web  # this is the key fix

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set up Node and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: molecule-web
        run: |
          corepack enable
          pnpm install

      - name: Build VuePress site
        working-directory: molecule-web
        run: pnpm docs:build

      - name: List built files (debug)
        working-directory: molecule-web
        run: ls -R docs/.vuepress/dist

      - name: Deploy to scalamolecule.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: scalamolecule/scalamolecule.github.io
          publish_branch: master
          publish_dir: molecule-web/docs/.vuepress/dist
          cname: www.scalamolecule.org